### ISSUE TITLE
Include LCSC part numbers as a symbol property

### ISSUE THREAD

**Issue by Alyssa3467** [TousstNicolas/JLC2KiCad_lib#11] opened 2022-05-04 14:14 UTC
Since JLCPCB wants LCSC part numbers in the BOM and it's one of the command line arguments, it might be beneficial to add that information to the symbol.

**Comment by TousstNicolas** [comment] 2022-05-05 16:44
Thanks for your issue. 

I Added the  property 'LCSC' to the symbol which contain the LCSC part number. It will now be present in the BOM. 
You can update the package from pip to get it the last version of the package. 

I will let you close it if the issue is solved for you.

**Closed** 2022-05-12 15:14 UTC
